configurations:

libs:
  face_cascade: 'libs/haarcascade_frontalface_default.xml'
  predictor: 'libs/shape_predictor_68_face_landmarks.dat'
  detector: 'libs/opencv_face_detector.pbtxt'
  detector-uint8: 'libs/opencv_face_detector_uint8.pb'

models:
  Vincenzo: 'models/Vincenzo/'
  Angelo: 'models/Angelo/'
  Dima: 'models/Dima/'
  Giovanna: 'models/Giovanna/'
  Noemi: 'models/Noemi/'

data:
  source_images: 'data/detectedFaces/source'
  destination_extracted_faces: 'data/detectedFaces/extracted_and_aligned_faces'
  training: 'data/trainingSet/'

features:
  with:
    Vincenzo: 'Vincenzo'
    Angelo: 'Angelo'
    Dima: 'Dima'
    Giovanna: 'Giovanna'
    Noemi: 'Noemi'
  without:
    Vincenzo: 'noVincenzo'
    Angelo: 'noAngelo'
    Dima: 'noDima'
    Giovanna: 'noGiovanna'
    Noemi: 'noNoemi'
